services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html
